### ISSUE TITLE
Request: Tint status bar depending on Album Art colors

### ISSUE THREAD

**Issue by K-orne** [Maxr1998/XGPM#2]
It would be nice to have the status bar similarly colored from the album art as buttons already are on the now playing screen. 

Cheers

**Comment by Maxr1998** [comment]
Sure, will take a look at it soon :)

**Comment by russjr08** [comment]
@Maxr1998 Any update on this? I think it'd go great with the new update! :D 

Edit: I've never worked with Xposed, but I think [this](https://github.com/Maxr1998/XGPM/blob/master/app/src/main/java/de/Maxr1998/xposed/gpm/hooks/NowPlaying.java#L209) would be a perfect place to add it. You'd just need to grab the window somehow (again, not sure how since I've never worked with xposed 😞 ), and call setStatusBarColor(lastColor). Seems like that'd work well!

**Comment by Maxr1998** [comment]
Yeah, I will take a look at it!
I might already know how to do it :P
